name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - name: Checkout Repository
      uses: actions/checkout@v3
    # Install Dependencies 
    - name: Install tools and utilities
      run: |
          sudo apt-get update \
          && sudo apt-get -y upgrade \
          && sudo apt-get install -y openconnect iputils-ping ocproxy openssh-client sshpass rsync make curl gettext-base \
    # Connect to VPN
    - name: Forticlient VPN
      run: |
           sudo openconnect -u ${{ secrets.VPN_USER }} --protocol=fortinet ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --servercert ${{ secrets.VPN_SERVER_CERT }} --passwd-on-stdin <<< "${{ secrets.VPN_PWD }}" &
           sleep 10
    # Execute Commands on Remote Server
    - name: Execute Commands on Remote Server 
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.INTERNAL_SERVER_IP }} << 'ENDSSH'
           cd ${{ secrets.DEPLOY_PATH }}
           touch file_from_git_actions.txt
           ENDSSH
