name: deploy
on: 
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install openconnect ppa
        run: sudo add-apt-repository ppa:dwmw2/openconnect -y && sudo apt update
      
      - name: Install openconnect
        run: sudo apt install -y expect openconnect
      
      - name: Connect to VPN
        run: |
          expect -c "
          spawn sudo openconnect -u ${{ secrets.VPN_USER }} --passwd-on-stdin --protocol=fortinet ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --servercert ${{ secrets.VPN_SERVER_CERT }}
          expect \"Password:\"
          send \"${{ secrets.VPN_PWD }}\r\"
          interact
          "
      - name: Test if connected to VPN
        run: |
          cd ${{ secrets.DEPLOY_PATH }}
          touch file_from_git_actions.txt
