# .github/workflows/vpn.yml
name: Can I use openconnect / fortinet on Github Actions?
on: push

jobs:
 openconnect:
   name: Build, install and run openconnect / fortinet
   runs-on: ubuntu-latest
   steps:
     # Checkout Repository
     - uses: actions/checkout@v3
     - name: Checkout Repository
       run: cp ./vpnc-script ./vpnc-script
     - name: Connect to VPN
       run: |
         echo ${{ secrets.VPN_PWD }} | sudo openconnect --script ./vpnc-script -u ${{ secrets.VPN_USER }} ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --protocol=fortinet --servercert ${{ secrets.VPN_SERVER_CERT }} --passwd-on-stdin
     - name: Test if connected to VPN
       run: |
         ping -c4 ${{ secrets.SERVER_HOST_INSIDE_VPN }}
